name: Permission
version: ${project.version}
main: com.mengcraft.permission.Main

commands:
  permission:
    description: Base command for permission manager.
    permission: permission.admin

permissions:
  permission.admin:
    description: Base permission for permission manager.
    default: op

depend: [SimpleORM]