name: Permission
version: ${project.version}
main: com.mengcraft.permission.Main

commands:
  permission:
    description: Base command for permission manager.
    permission: permission.use

permissions:
  permission.use:
    description: Basic usage permission.
    default: op
  permission.admin:
    description: Operator permission for permission manager.
    default: op

depend: [SimpleORM]